# eval = TRUE, and the lint enforces it.
#
# This was FALSE, globally, with 145 chunks specified against it and no check.
# The failure is silent and total: a figure chunk that does not evaluate produces
# no figure, and knitr drops its caption, its fig.alt and its `fig:` anchor with
# it -- so the figure vanishes from the book's numbering and every \@ref() to it
# resolves to nothing, with the build green. The book's premise is that every
# number is computed at render time; a default that quietly computes none of them
# is the wrong way round.
#
# A chunk that must be shown without running says so per chunk, with
# `eval = FALSE` and a label beginning `norun-`. scripts/lint-chapters.R rejects
# any other eval = FALSE, and rejects it outright on a chunk that makes a figure.
knitr::opts_chunk$set(
  echo       = TRUE,
  eval       = TRUE,
  message    = FALSE,
  warning    = FALSE,
  cache      = FALSE,
  fig.align  = "center",
  fig.width  = 7,
  fig.height = 4.5,
  fig.retina = 2,
  dpi        = 300,
  out.width  = "90%",
  comment    = "#>"
)

options(
  scipen = 999,
  digits = 3,
  knitr.kable.NA = "—"
)

set.seed(42)

# NOTE — do not copy the tweak_part_screwup() no-op from methods-in-r.
# That volume patches bookdown::tweak_part_screwup() to a no-op, working around
# a crash in bookdown 0.46 (`xml_attr(parent, "class") == "row"` yields NA when
# the parent div has no class attribute). The bug is fixed in 0.47, and applying
# the patch here silently suppresses ALL part headings: "(PART) Part I — Folding"
# renders to nothing, in the sidebar and in the body. Verified by rendering both
# ways: 0 occurrences of "Part I" with the patch, 98 without it.
# If a future bookdown reintroduces the crash, guard the patch on
# packageVersion("bookdown") rather than restoring it unconditionally.

# ── Book helpers ────────────────────────────────────────────────────────────
# The code this book runs on lives in R/ as plain scripts, sourced here. There
# is no companion package: no install step, and no version of the helpers that
# can drift from the version the chapters were written against.
#
# Sourcing is tolerant of an empty R/ while chapters are still being written —
# every chunk is eval = FALSE until then, so nothing calls a helper. Once the
# first chapter goes live this should become a hard error, exactly as in
# scientometrics-in-r/_common.R.
local({
  helpers <- sort(list.files("R", pattern = "\\.R$", full.names = TRUE))
  if (!length(helpers)) {
    message("_common.R: no helper scripts in R/ yet — scaffold mode.")
  } else {
    for (f in helpers) source(f, local = FALSE)
  }
})

# ── Series conventions ──────────────────────────────────────────────────────
# One viridis option per volume, so figures stay visually separable when
# chapters from different books sit side by side.
#   strategy-in-r = "D"   scientometrics-in-r = "A"   folding-in-r = "C" (plasma)
scale_fill_book  <- function(...) viridis::scale_fill_viridis_d(option = "C", ...)
scale_color_book <- function(...) viridis::scale_color_viridis_d(option = "C", ...)
scale_colour_book <- scale_color_book

# Every stochastic result in this book is reported across seeds, never from a
# single run — t-SNE and UMAP are seed-dependent and one run is an anecdote.
# See "How to use this book".
N_SEEDS     <- 20L
BENCH_SEEDS <- 1000L + seq_len(N_SEEDS)

# packages.bib is NOT written here. _bookdown.yml sets new_session: yes with
# before_chapter_script: "_common.R", so this file runs once per source file --
# a write_bib() call at the bottom of it overwrote the bibliography 22 times
# per render, each time from a different .packages(), and the surviving file
# described whichever chapter knitted last. It is generated by
# scripts/write-package-bib.R from a hand-maintained vector and committed like
# any other artefact. See that script's header.
