#!/usr/bin/env Rscript
#
# Generate packages.bib -- the R-package half of the bibliography.
#
# This used to live at the bottom of _common.R, which was wrong in a way that
# was invisible until you looked for it. _bookdown.yml sets new_session: yes
# with before_chapter_script: "_common.R", so _common.R runs once per source
# file -- 22 times -- and its final statement overwrote packages.bib on every
# one of them. The vector it passed began with .packages(), which differs per
# chapter, so the surviving file described whichever chapter happened to knit
# last. index.Rmd declares bibliography: [book.bib, packages.bib], so @R-uwot
# cited in Chapter 6 resolved to nothing whenever Chapter 12 knitted last. The
# committed file still carries the fingerprint: R-fs and R-yaml are in it
# because some chapter loaded fs and yaml, not because the book cites them.
#
# The vector below is therefore hand-maintained. Never .packages() -- that is
# precisely what made the output session-dependent.
#
# Usage:
#   Rscript scripts/write-package-bib.R           # regenerate packages.bib
#   Rscript scripts/write-package-bib.R --check    # verify it is up to date
#
# Run the plain form locally, inside the renv project, and commit the result:
# packages.bib is an artefact like the benchmark grid, not a build product. CI
# runs --check, which compares only the entries it can actually see and never
# rewrites the file -- so a package missing from the CI library (torch) leaves
# its entry alone instead of silently deleting it.

## ── The vector ──────────────────────────────────────────────────────────────
# Packages the book cites in its own text. Adding a package to renv.lock does
# not put it here; citing it in a chapter does.

PKGS <- c(
  "base",
  "bookdown", "knitr", "rmarkdown",      # the build
  "ggplot2", "viridis",                  # figures
  "Matrix", "RSpectra",                  # linear algebra
  "igraph", "vegan",                     # graphs and geodesics (Ch 5)
  "Rtsne", "umap"                        # neighbour embeddings (Ch 6)
)

# Recorded in renv.lock and cited by the book, but deliberately not installed
# everywhere: torch pulls a large binary backend and only Chapter 7 needs it,
# so render-book.yml restores with exclude = "torch". A missing optional
# package is a warning here, never a deletion.
PKGS_OPTIONAL <- c("torch")

OUT <- "packages.bib"

## ── Machinery ───────────────────────────────────────────────────────────────

args  <- commandArgs(trailingOnly = TRUE)
check <- "--check" %in% args

installed <- function(p) {
  p == "base" || nzchar(system.file(package = p))
}

missing_required <- PKGS[!vapply(PKGS, installed, logical(1))]
if (length(missing_required)) {
  stop("not installed, so their citations cannot be generated: ",
       paste(missing_required, collapse = ", "),
       "\n  Run renv::restore() first. These are required, not optional: a bib ",
       "entry\n  written from memory is exactly what CONTRIBUTING.md forbids.",
       call. = FALSE)
}

have_optional <- PKGS_OPTIONAL[vapply(PKGS_OPTIONAL, installed, logical(1))]
skip_optional <- setdiff(PKGS_OPTIONAL, have_optional)
if (length(skip_optional)) {
  message("optional and not installed, existing entries left untouched: ",
          paste(skip_optional, collapse = ", "))
}

# Split a bib file into blocks keyed by cite key. knitr::write_bib emits one
# @type{key, ... } block per entry, opening in column 0 and closing on a line
# that is exactly "}".
read_blocks <- function(path) {
  if (!file.exists(path)) return(list())
  lines <- readLines(path, warn = FALSE)
  starts <- grep("^@[A-Za-z]+\\{", lines)
  if (!length(starts)) return(list())
  ends <- c(starts[-1] - 1L, length(lines))
  blocks <- Map(function(a, b) {
    blk <- lines[a:b]
    while (length(blk) && !nzchar(trimws(blk[length(blk)]))) blk <- blk[-length(blk)]
    blk
  }, starts, ends)
  keys <- sub("^@[A-Za-z]+\\{([^,]+),.*$", "\\1", lines[starts])
  stats::setNames(blocks, keys)
}

tmp <- tempfile(fileext = ".bib")
on.exit(unlink(tmp), add = TRUE)
knitr::write_bib(c(PKGS, have_optional), tmp, tweak = TRUE)

fresh    <- read_blocks(tmp)
existing <- read_blocks(OUT)

# Carry over entries belonging to packages we could not see this run. Match on
# the R-<pkg> key and on any key write_bib derived from that package's own
# CITATION file, which it names <pkg><year>.
carried <- character(0)
if (length(skip_optional)) {
  pat <- paste0("^(R-)?(", paste(skip_optional, collapse = "|"), ")[0-9]*$")
  carried <- grep(pat, names(existing), value = TRUE)
}

out_blocks <- c(fresh, existing[carried])
out_blocks <- out_blocks[order(tolower(names(out_blocks)))]

header <- c(
  "% Generated by scripts/write-package-bib.R -- do not edit by hand.",
  "% The package vector is maintained in that script, not here.",
  ""
)
body <- unlist(lapply(out_blocks, function(b) c(b, "")), use.names = FALSE)
new_text <- c(header, body)

if (check) {
  # Compare per entry, not per line, so an entry for a package this library
  # cannot see is never counted as a difference.
  old_blocks <- read_blocks(OUT)
  visible <- names(fresh)
  gone    <- setdiff(visible, names(old_blocks))
  changed <- setdiff(visible, gone)
  changed <- changed[!vapply(changed, function(k) identical(fresh[[k]], old_blocks[[k]]),
                             logical(1))]
  if (length(gone) || length(changed)) {
    stop("packages.bib is out of date.",
         if (length(gone))    paste0("\n  missing: ", paste(gone, collapse = ", ")) else "",
         if (length(changed)) paste0("\n  changed: ", paste(changed, collapse = ", ")) else "",
         "\n  Run: Rscript scripts/write-package-bib.R  and commit the result.",
         call. = FALSE)
  }
  message("packages.bib is up to date -- ", length(visible), " entries checked, ",
          length(carried), " carried.")
} else {
  writeLines(new_text, OUT)
  message("wrote ", OUT, " -- ", length(out_blocks), " entries (",
          length(fresh), " generated, ", length(carried), " carried).")
}
